/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTvRouteImport } from './routes/_authenticated/tv'
import { Route as AuthenticatedSgfRouteImport } from './routes/_authenticated/sgf'
import { Route as AuthenticatedReunioesRouteImport } from './routes/_authenticated/reunioes'
import { Route as AuthenticatedQuiosqueRouteImport } from './routes/_authenticated/quiosque'
import { Route as AuthenticatedQuadroIosRouteImport } from './routes/_authenticated/quadro-ios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedPesquisaRouteImport } from './routes/_authenticated/pesquisa'
import { Route as AuthenticatedPdsRouteImport } from './routes/_authenticated/pds'
import { Route as AuthenticatedOciosidadeRouteImport } from './routes/_authenticated/ociosidade'
import { Route as AuthenticatedNpsRouteImport } from './routes/_authenticated/nps'
import { Route as AuthenticatedHorariosRouteImport } from './routes/_authenticated/horarios'
import { Route as AuthenticatedDesempenhoRouteImport } from './routes/_authenticated/desempenho'
import { Route as AuthenticatedDesafiosRouteImport } from './routes/_authenticated/desafios'
import { Route as AuthenticatedContadorRouteImport } from './routes/_authenticated/contador'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedAusenciasRouteImport } from './routes/_authenticated/ausencias'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedIndividualIndexRouteImport } from './routes/_authenticated/individual.index'
import { Route as AuthenticatedIndividualSlugRouteImport } from './routes/_authenticated/individual.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTvRoute = AuthenticatedTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSgfRoute = AuthenticatedSgfRouteImport.update({
  id: '/sgf',
  path: '/sgf',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReunioesRoute = AuthenticatedReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuiosqueRoute = AuthenticatedQuiosqueRouteImport.update({
  id: '/quiosque',
  path: '/quiosque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuadroIosRoute = AuthenticatedQuadroIosRouteImport.update({
  id: '/quadro-ios',
  path: '/quadro-ios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesquisaRoute = AuthenticatedPesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdsRoute = AuthenticatedPdsRouteImport.update({
  id: '/pds',
  path: '/pds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOciosidadeRoute = AuthenticatedOciosidadeRouteImport.update({
  id: '/ociosidade',
  path: '/ociosidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNpsRoute = AuthenticatedNpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHorariosRoute = AuthenticatedHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesempenhoRoute = AuthenticatedDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesafiosRoute = AuthenticatedDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContadorRoute = AuthenticatedContadorRouteImport.update({
  id: '/contador',
  path: '/contador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAusenciasRoute = AuthenticatedAusenciasRouteImport.update({
  id: '/ausencias',
  path: '/ausencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndividualIndexRoute =
  AuthenticatedIndividualIndexRouteImport.update({
    id: '/individual/',
    path: '/individual/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndividualSlugRoute =
  AuthenticatedIndividualSlugRouteImport.update({
    id: '/individual/$slug',
    path: '/individual/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/contador': typeof AuthenticatedContadorRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/nps': typeof AuthenticatedNpsRoute
  '/ociosidade': typeof AuthenticatedOciosidadeRoute
  '/pds': typeof AuthenticatedPdsRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/quadro-ios': typeof AuthenticatedQuadroIosRoute
  '/quiosque': typeof AuthenticatedQuiosqueRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
  '/sgf': typeof AuthenticatedSgfRoute
  '/tv': typeof AuthenticatedTvRoute
  '/individual/$slug': typeof AuthenticatedIndividualSlugRoute
  '/individual/': typeof AuthenticatedIndividualIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/contador': typeof AuthenticatedContadorRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/horarios': typeof AuthenticatedHorariosRoute
  '/nps': typeof AuthenticatedNpsRoute
  '/ociosidade': typeof AuthenticatedOciosidadeRoute
  '/pds': typeof AuthenticatedPdsRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/quadro-ios': typeof AuthenticatedQuadroIosRoute
  '/quiosque': typeof AuthenticatedQuiosqueRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
  '/sgf': typeof AuthenticatedSgfRoute
  '/tv': typeof AuthenticatedTvRoute
  '/': typeof AuthenticatedIndexRoute
  '/individual/$slug': typeof AuthenticatedIndividualSlugRoute
  '/individual': typeof AuthenticatedIndividualIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ausencias': typeof AuthenticatedAusenciasRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/contador': typeof AuthenticatedContadorRoute
  '/_authenticated/desafios': typeof AuthenticatedDesafiosRoute
  '/_authenticated/desempenho': typeof AuthenticatedDesempenhoRoute
  '/_authenticated/horarios': typeof AuthenticatedHorariosRoute
  '/_authenticated/nps': typeof AuthenticatedNpsRoute
  '/_authenticated/ociosidade': typeof AuthenticatedOciosidadeRoute
  '/_authenticated/pds': typeof AuthenticatedPdsRoute
  '/_authenticated/pesquisa': typeof AuthenticatedPesquisaRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/quadro-ios': typeof AuthenticatedQuadroIosRoute
  '/_authenticated/quiosque': typeof AuthenticatedQuiosqueRoute
  '/_authenticated/reunioes': typeof AuthenticatedReunioesRoute
  '/_authenticated/sgf': typeof AuthenticatedSgfRoute
  '/_authenticated/tv': typeof AuthenticatedTvRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/individual/$slug': typeof AuthenticatedIndividualSlugRoute
  '/_authenticated/individual/': typeof AuthenticatedIndividualIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/ausencias'
    | '/avisos'
    | '/colaboradores'
    | '/configuracoes'
    | '/conquistas'
    | '/contador'
    | '/desafios'
    | '/desempenho'
    | '/horarios'
    | '/nps'
    | '/ociosidade'
    | '/pds'
    | '/pesquisa'
    | '/produtos'
    | '/quadro-ios'
    | '/quiosque'
    | '/reunioes'
    | '/sgf'
    | '/tv'
    | '/individual/$slug'
    | '/individual/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/ausencias'
    | '/avisos'
    | '/colaboradores'
    | '/configuracoes'
    | '/conquistas'
    | '/contador'
    | '/desafios'
    | '/desempenho'
    | '/horarios'
    | '/nps'
    | '/ociosidade'
    | '/pds'
    | '/pesquisa'
    | '/produtos'
    | '/quadro-ios'
    | '/quiosque'
    | '/reunioes'
    | '/sgf'
    | '/tv'
    | '/'
    | '/individual/$slug'
    | '/individual'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/ausencias'
    | '/_authenticated/avisos'
    | '/_authenticated/colaboradores'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conquistas'
    | '/_authenticated/contador'
    | '/_authenticated/desafios'
    | '/_authenticated/desempenho'
    | '/_authenticated/horarios'
    | '/_authenticated/nps'
    | '/_authenticated/ociosidade'
    | '/_authenticated/pds'
    | '/_authenticated/pesquisa'
    | '/_authenticated/produtos'
    | '/_authenticated/quadro-ios'
    | '/_authenticated/quiosque'
    | '/_authenticated/reunioes'
    | '/_authenticated/sgf'
    | '/_authenticated/tv'
    | '/_authenticated/'
    | '/_authenticated/individual/$slug'
    | '/_authenticated/individual/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tv': {
      id: '/_authenticated/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AuthenticatedTvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sgf': {
      id: '/_authenticated/sgf'
      path: '/sgf'
      fullPath: '/sgf'
      preLoaderRoute: typeof AuthenticatedSgfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reunioes': {
      id: '/_authenticated/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AuthenticatedReunioesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiosque': {
      id: '/_authenticated/quiosque'
      path: '/quiosque'
      fullPath: '/quiosque'
      preLoaderRoute: typeof AuthenticatedQuiosqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quadro-ios': {
      id: '/_authenticated/quadro-ios'
      path: '/quadro-ios'
      fullPath: '/quadro-ios'
      preLoaderRoute: typeof AuthenticatedQuadroIosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesquisa': {
      id: '/_authenticated/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof AuthenticatedPesquisaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pds': {
      id: '/_authenticated/pds'
      path: '/pds'
      fullPath: '/pds'
      preLoaderRoute: typeof AuthenticatedPdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ociosidade': {
      id: '/_authenticated/ociosidade'
      path: '/ociosidade'
      fullPath: '/ociosidade'
      preLoaderRoute: typeof AuthenticatedOciosidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nps': {
      id: '/_authenticated/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof AuthenticatedNpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horarios': {
      id: '/_authenticated/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof AuthenticatedHorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desempenho': {
      id: '/_authenticated/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof AuthenticatedDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafios': {
      id: '/_authenticated/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof AuthenticatedDesafiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contador': {
      id: '/_authenticated/contador'
      path: '/contador'
      fullPath: '/contador'
      preLoaderRoute: typeof AuthenticatedContadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ausencias': {
      id: '/_authenticated/ausencias'
      path: '/ausencias'
      fullPath: '/ausencias'
      preLoaderRoute: typeof AuthenticatedAusenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/individual/': {
      id: '/_authenticated/individual/'
      path: '/individual'
      fullPath: '/individual/'
      preLoaderRoute: typeof AuthenticatedIndividualIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/individual/$slug': {
      id: '/_authenticated/individual/$slug'
      path: '/individual/$slug'
      fullPath: '/individual/$slug'
      preLoaderRoute: typeof AuthenticatedIndividualSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAusenciasRoute: typeof AuthenticatedAusenciasRoute
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedContadorRoute: typeof AuthenticatedContadorRoute
  AuthenticatedDesafiosRoute: typeof AuthenticatedDesafiosRoute
  AuthenticatedDesempenhoRoute: typeof AuthenticatedDesempenhoRoute
  AuthenticatedHorariosRoute: typeof AuthenticatedHorariosRoute
  AuthenticatedNpsRoute: typeof AuthenticatedNpsRoute
  AuthenticatedOciosidadeRoute: typeof AuthenticatedOciosidadeRoute
  AuthenticatedPdsRoute: typeof AuthenticatedPdsRoute
  AuthenticatedPesquisaRoute: typeof AuthenticatedPesquisaRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedQuadroIosRoute: typeof AuthenticatedQuadroIosRoute
  AuthenticatedQuiosqueRoute: typeof AuthenticatedQuiosqueRoute
  AuthenticatedReunioesRoute: typeof AuthenticatedReunioesRoute
  AuthenticatedSgfRoute: typeof AuthenticatedSgfRoute
  AuthenticatedTvRoute: typeof AuthenticatedTvRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedIndividualSlugRoute: typeof AuthenticatedIndividualSlugRoute
  AuthenticatedIndividualIndexRoute: typeof AuthenticatedIndividualIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAusenciasRoute: AuthenticatedAusenciasRoute,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedContadorRoute: AuthenticatedContadorRoute,
  AuthenticatedDesafiosRoute: AuthenticatedDesafiosRoute,
  AuthenticatedDesempenhoRoute: AuthenticatedDesempenhoRoute,
  AuthenticatedHorariosRoute: AuthenticatedHorariosRoute,
  AuthenticatedNpsRoute: AuthenticatedNpsRoute,
  AuthenticatedOciosidadeRoute: AuthenticatedOciosidadeRoute,
  AuthenticatedPdsRoute: AuthenticatedPdsRoute,
  AuthenticatedPesquisaRoute: AuthenticatedPesquisaRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedQuadroIosRoute: AuthenticatedQuadroIosRoute,
  AuthenticatedQuiosqueRoute: AuthenticatedQuiosqueRoute,
  AuthenticatedReunioesRoute: AuthenticatedReunioesRoute,
  AuthenticatedSgfRoute: AuthenticatedSgfRoute,
  AuthenticatedTvRoute: AuthenticatedTvRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedIndividualSlugRoute: AuthenticatedIndividualSlugRoute,
  AuthenticatedIndividualIndexRoute: AuthenticatedIndividualIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
